django_test/articles/urls.py
from django.urls import path, include
from articles import views

app_name = 'articles'
urlpatterns = [
    path('', views.main_page, name = 'index'),
    path('<int:id>/', views.article_description, name = 'article'),
    path('add/', views.article_add, name='article_add'),
    path('tags/', views.TagListView.as_view(), name='tag_list'),
    path('tag_one/<int:pk>', views.TagDetailView.as_view(), name='tag_one'),
    path('tag_update/<int:pk>', views.TagUpdateView.as_view(), name='tag_update'),
    path('tag_delete/<int:pk>', views.TagDeleteView.as_view(), name='tag_delete'),
    path('tag_create/', views.TagCreateView.as_view(), name='tag_create'),

]

django_test/django_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django_test import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_test/users/urls.py
from django.urls import path, include
from users import views
from django.contrib.auth.views import LogoutView


app_name = 'users'
urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', views.UserCreateView.as_view(), name='register'),

]

django_test/articles/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)

class IsActiveMixin(models.Model):
    objects = models.Manager()
    active_objects = ActiveManager()
    is_active = models.BooleanField(default=False)
    class Meta:
        abstract = True

class Tag(IsActiveMixin, models.Model):
    tag_name = models.CharField(max_length = 100)

    def __str__(self):
        return f'{self.tag_name}'

class Article(IsActiveMixin,models.Model):
    article_name = models.CharField(max_length = 100, null= True)
    article_text = models.CharField(max_length = 1000, null=True)
    article_date = models.DateTimeField(default=datetime.now())
    article_tag = models.ManyToManyField(Tag)
    article_img = models.ImageField(upload_to = 'articles', null = True, blank = True)
    article_rating = models.IntegerField(default = 0, null=True)

    '''
    DataField - дата
    TimeField - время
    
    Числовые типы:
    IntegerField 
    PositiveIntegerField
    FloatField
    
    Логические типы:
    BooleanField
    
    Байтовый тип:
    BinaryField
    
    Email:
    EmailField
    
    URL:
    URLField
    
    Image:
    ImageField
    
    '''
    def __str__(self):
        return f'{self.article_name}, published: {self.article_date}'

django_test/articles/forms.py
from django import forms
from .models import Tag, Article



# class ArticleForm(forms.Form):
#     name = forms.CharField(label = 'Название статьи', max_length=100)
#     text = forms.CharField(label = 'Текст статьи')
#     tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.CheckboxSelectMultiple())

class ArticleForm(forms.ModelForm):
    article_name = forms.CharField(label='Название статьи')

    class Meta:
        model = Article
        fields = '__all__'
        # fields = ('article_name','article_text')
        # exclude = ('tags')

django_test/articles/views.py
from django.core.files.images import ImageFile
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from .models import Article, Tag
import random
from datetime import datetime
from .forms import ArticleForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def main_page(request):
    # art_all = Article.objects.all()
    # art_all = Article.objects.filter(is_active=True)
    art_all = Article.active_objects.all()


    paginator = Paginator(art_all, 2)  # Show 2 contacts per page

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articles = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articles = paginator.page(paginator.num_pages)

    #return HttpResponse(f'Number of articles: {len(art_all)}')
    #return render(request, 'articles/articles_main.html', {'articles': art_all})
    return render(request, 'articles/category.html', {'articles': articles})

@login_required
def article_description(request, id):
    #art_one = Article.objects.first()
    #return HttpResponse(f'Text: {art_one.article_text}')
    art_one = get_object_or_404(Article, id = id)
    return render(request, 'articles/single.html', {'article': art_one})

@user_passes_test(lambda user: user.is_superuser)
def article_add(request):
    if request.method == 'GET':
        form = ArticleForm()
        return render(request, 'articles/article_add.html', {'form':form})
    else:
        #form = ArticleForm(request.POST)
        form = ArticleForm(request.POST, files = request.FILES)
        if form.is_valid():
            # обработка данных

            '''
            # первый способ создания формы
            name = form.cleaned_data['name']
            text = form.cleaned_data['text']
            tags = form.cleaned_data['tags']
            print(f'{name},{text},{tags}')
            article_object = Article.objects.create(article_name =name, article_text=text, article_date= datetime.now(), article_img= ImageFile(open("media/articles/hello_world.jpeg", "rb")))
            article_object.save()
            '''
            # второй способ создания формы

            form.save()
            return HttpResponseRedirect(reverse('articles:index'))
        else:
            return render(request, 'articles/article_add.html', {'form':form})

class TagListView(ListView):
    model = Tag
    template_name = 'articles/tag_list.html'
    context_object_name = 'tags'
    paginate_by = 2

    def get_queryset(self):
    # #можно наложить условия на объекты
        return Tag.active_objects.all()
    # return Tag.objects.filter(is_active = True)

class TagDetailView(LoginRequiredMixin, DetailView):
    model = Tag
    template_name = 'articles/tag_one.html'


class PermissionMixin:

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse('articles:index'))

class TagUpdateView(PermissionMixin, UserPassesTestMixin, UpdateView):
    model = Tag
    fields = '__all__'
    template_name = 'articles/tag_update.html'
    success_url = reverse_lazy('articles:tag_list')

class TagDeleteView(PermissionMixin, UserPassesTestMixin, DeleteView):
    template_name =  'articles/tag_delete.html'
    model = Tag
    success_url = reverse_lazy('articles:tag_list')

class TagCreateView(PermissionMixin, UserPassesTestMixin, CreateView):
    model = Tag
    fields = '__all__'
    template_name = 'articles/tag_create.html'
    success_url = reverse_lazy('articles:tag_list')

django_test/articles/templates/articles/article_add.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

          <div class="col-md-4">
              <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    {#form#}
                  {% for field in form %}
                  <p>{{field.label_tag}}</p>
                  <hr>
                  {% for error in field.errors %}
                    {{error}}
                  {% endfor %}
                  <p>{{field}}</p>
                  {% endfor %}
                  <button type="submit">Добавить статью</button>

              </form>
          </div>
        </div>
      <div class="text"></div>

      </div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/article_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>One article</title>
</head>
<body>
{{article.article_text}}
</body>
</html>

django_test/articles/templates/articles/articles_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All articles</title>
</head>
<body>
    <ul>
        {% for article in articles.all%}
        <li><a href = "{{article.id}}">{{article.article_name}}</a>, published {{article.article_date}}</li>
        <li><a href = "{% url 'articles:article' id=article.id %}">{{article.article_name}}</a>, published {{article.article_date}}</li>
        {% endfor %}
    </ul>
</body>
</html>

django_test/articles/templates/articles/base.html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <title>Mini Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">
{% load static %}
    <link rel="stylesheet" href="{% static "articles/style.css" %}">
    <link rel="stylesheet" href="{% static "articles/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "articles/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "articles/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "articles/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "articles/aos.css" %}">

    <link rel="stylesheet" href="{% static "articles/style.css" %}">
  </head>
  <body>
  
  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    
    <header class="site-navbar" role="banner">
      <div class="container-fluid">
        <div class="row align-items-center">
          
          <div class="col-12 search-form-wrap js-search-form">
            <form method="get" action="#">
              <input type="text" id="s" class="form-control" placeholder="Search...">
              <button class="search-btn" type="submit"><span class="icon-search"></span></button>
            </form>
          </div>

          <div class="col-4 site-logo">
            <a href="index.html" class="text-black h2 mb-0">Mini Blog</a>
          </div>

          <div class="col-8 text-right">
            <nav class="site-navigation" role="navigation">
              <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block mb-0">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'articles:index' %}">Articles</a></li>
                <li><a href="{% url 'articles:article_add' %}">Add article</a></li>
                <li><a href="{% url 'articles:tag_list' %}">Tags</a></li>
                {% if user.is_authenticated %}
                Рады приветствовать, {{user.username}}!
                <li><a href="{% url 'users:logout' %}">Exit</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">Auth</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}

                <li class="d-none d-lg-inline-block"><a href="#" class="js-search-toggle"><span class="icon-search"></span></a></li>
              </ul>
            </nav>
            <a href="#" class="site-menu-toggle js-menu-toggle text-black d-inline-block d-lg-none"><span class="icon-menu h3"></span></a></div>
          </div>

      </div>
    </header>
    
    
{% block content %} {% endblock %}


    
    <div class="site-footer">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-4">
            <h3 class="footer-heading mb-4">About Us</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Placeat reprehenderit magnam deleniti quasi saepe, consequatur atque sequi delectus dolore veritatis obcaecati quae, repellat eveniet omnis, voluptatem in. Soluta, eligendi, architecto.</p>
          </div>
          <div class="col-md-3 ml-auto">
            <!-- <h3 class="footer-heading mb-4">Navigation</h3> -->
            <ul class="list-unstyled float-left mr-5">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Advertise</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#">Subscribes</a></li>
            </ul>
            <ul class="list-unstyled float-left">
              <li><a href="#">Travel</a></li>
              <li><a href="#">Lifestyle</a></li>
              <li><a href="#">Sports</a></li>
              <li><a href="#">Nature</a></li>
            </ul>
          </div>
          <div class="col-md-4">
            

            <div>
              <h3 class="footer-heading mb-4">Connect With Us</h3>
              <p>
                <a href="#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
                <a href="#"><span class="icon-twitter p-2"></span></a>
                <a href="#"><span class="icon-instagram p-2"></span></a>
                <a href="#"><span class="icon-rss p-2"></span></a>
                <a href="#"><span class="icon-envelope p-2"></span></a>
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12 text-center">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
          </div>
        </div>
      </div>
    </div>
    
  </div>



  </body>
</html>

django_test/articles/templates/articles/category.html
{% extends "articles/base.html" %}


{% block content %}
    
    <div class="py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <span>Category</span>
            <h3>All articles</h3>
            <p>The most important articles are collected here!</p>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-white">
      <div class="container">
        <div class="row">
          {% for article in articles %}
          <div class="col-lg-4 mb-4">
            <div class="entry2">
              <a href="{% url 'articles:article' id=article.id %}"><img src="{{article.article_img.url}}" alt="Image" class="img-fluid rounded"></a>
              <div class="excerpt">

              <h2><a href="{% url 'articles:article' id=article.id %}">{{article.article_name}}</a></h2>
              <div class="post-meta align-items-center text-left clearfix">
                <figure class="author-figure mb-0 mr-3 float-left"><img src="images/person_1.jpg" alt="Image" class="img-fluid"></figure>
                <span>&nbsp;-&nbsp; {{article.article_date}}</span>
              </div>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
        <div class="pagination">
    <span class="step-links">
        {% if articles.has_previous %}
            <a href="?page={{ articles.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
        </span>

        {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

    </div>
  </div>
    
{% endblock %}

django_test/articles/templates/articles/index.html
{% extends "articles/base.html" %}


{% block content %}
    
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">


          <div class="col-md-4">


            <a href="{% url 'articles:article' id=article.id %}" class="h-entry mb-30 v-height gradient" style="background-image: url('images/img_3.jpg');">
              
              <div class="text">
                <h2>The most popular article: </h2>
                <h2>{{article.article_name}}</h2>
                <span class="date">{{article.article_date}}</span>
              </div>
            </a>
          </div>
        </div>
                              <div class="text">{{article.article_text}}</div>

      </div>
    </div>

{% endblock %}

django_test/articles/templates/articles/single.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

          <div class="col-md-4">

            <a href="{% url 'articles:article' id=article.id %}" class="h-entry mb-30 v-height gradient" style="background-image: url('images/img_4.jpg');"><img src="{{article.article_img.url}}" alt="Image" class="img-fluid rounded">
<!--              <a href="{% url 'articles:article' id=article.id %}"><img src="{{article.article_img.url}}" alt="Image" class="img-fluid rounded"></a>-->

                <div class="text">
                <h2>{{article.article_name}}</h2>
                <span class="date"> {{article.article_date}}</span>
              </div>
            </a>
          </div>
        </div>
                      <div class="text">{{article.article_text}}</div>

      </div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/tag_create.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                <button type="submit" class="btn btn_primary">Сохранить</button>
             </form >

        </div>

      </div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/tag_delete.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                <button type="submit" class="btn btn_primary">Сохранить</button>
             </form >

        </div>

      </div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/tag_list.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <ul>
            {% for tag in tags %}
                <li>
                    <a href = "{% url 'articles:tag_one' pk=tag.pk%}">{{tag.tag_name}}</a>
                </li>
            {% endfor %}
            </ul>

        </div>
            <a href="{% url 'articles:tag_create'%}">Создать тег</a>

      </div>
        <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/tag_one.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <ul style="list-style-type:none">
                <li>
                    {{tag.tag_name}}
                </li>
                <li>
                    <a href="{% url 'articles:tag_update' pk=tag.pk%}">Изменить</a>
                </li>
                <li>
                    <a href="{% url 'articles:tag_delete' pk=tag.pk%}">Удалить</a>
                </li>
            </ul>

        </div>

      </div>
    </div>

{% endblock %}

    

django_test/articles/templates/articles/tag_update.html
{% extends "articles/base.html" %}


{% block content %}

    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}

                <button type="submit" class="btn btn_primary">Сохранить</button>
             </form >

        </div>

      </div>
    </div>

{% endblock %}

    